services:
  dev-api:
    build:
      context: .
      target: development
    container_name: dev_api
    command: >
      sh -c "pnpm prisma migrate deploy && 
             pnpm prisma db seed && 
             pnpm start:dev"
    ports:
      - '3001:3000'
    env_file:
      - .env.development
    depends_on:
      dev-db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./generated:/app/generated
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - dev_node_modules:/app/node_modules # Prevents local node_modules from overwriting container's
    networks:
      - infra_net
  dev-db:
    image: postgres:16-alpine
    container_name: dev_db
    ports:
      - '5431:5432'
    env_file:
      - .env.development
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - infra_net
  dev-redis:
    image: redis:7-alpine
    container_name: dev_redis
    command: redis-server --appendonly yes
    volumes:
      - dev_redis_data:/data
    ports:
      - '6378:6379'
    networks:
      - infra_net
volumes:
  dev_db_data:
  dev_redis_data:
  dev_node_modules:
networks:
  infra_net:
    driver: bridge
