services:
  test-db:
    image: postgres:17-alpine
    container_name: test_db
    ports:
      - '5430:5432'
    env_file:
      - .env.test
    volumes:
      - test_db_data:/var/lib/postgresql/data
    networks:
      - infra_net
  test-redis:
    image: redis:7-alpine
    container_name: test_redis
    command: redis-server --appendonly yes
    ports:
      - '6377:6379'
    networks:
      - infra_net
volumes:
  test_db_data:
networks:
  infra_net:
    driver: bridge
